class Stack():
    def __init__(self) -> None: ...
    def push(self, x: T) -> None: ...
    def pop(self) -> T: ...
    def peek(self) -> T: ...
    def clear(self) -> T: ...
    def __len__(self) -> int: ...